Repository Poorlex/BE_poorlex, pull requests merged in 2023-08, with the labels that each got.

#2 [#1] chore: 자동리뷰어 설정
  .github/CODEOWNERS
Labels: 👷‍♀️ chore

#4 [#3] chore: PR 템플릿 설정
  .github/pull_request_template.md
Labels: 👷‍♀️ chore

#6 [#5] chore: 소셜로그인을 위한 Gradle 의존성 추가, yml profile에 따른 분리
  build.gradle
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 👷‍♀️ chore

#8 [#7] feature: 엔티티 설정 및 JpaAuditingConfig 분리
  src/main/java/com/project/poorlex/config/JpaAuditingConfig.java
  src/main/java/com/project/poorlex/domain/BaseEntity.java
  src/main/java/com/project/poorlex/domain/battle/Battle.java
  src/main/java/com/project/poorlex/domain/battle/BattleRepository.java
  src/main/java/com/project/poorlex/domain/battleuser/BattleUser.java
  src/main/java/com/project/poorlex/domain/battleuser/BattleUserRepository.java
  src/main/java/com/project/poorlex/domain/battleuser/Role.java
  src/main/java/com/project/poorlex/domain/budget/Budget.java
  src/main/java/com/project/poorlex/domain/budget/BudgetRepository.java
  src/main/java/com/project/poorlex/domain/chat/Chat.java
  src/main/java/com/project/poorlex/domain/chat/ChatRepository.java
  src/main/java/com/project/poorlex/domain/feedback/Feedback.java
  src/main/java/com/project/poorlex/domain/feedback/FeedbackRepository.java
  src/main/java/com/project/poorlex/domain/feedback/Reaction.java
  src/main/java/com/project/poorlex/domain/friend/Friend.java
  src/main/java/com/project/poorlex/domain/friend/FriendRepository.java
  src/main/java/com/project/poorlex/domain/goal/Goal.java
  src/main/java/com/project/poorlex/domain/goal/GoalRepository.java
  src/main/java/com/project/poorlex/domain/member/Member.java
  src/main/java/com/project/poorlex/domain/member/MemberRepository.java
  src/main/java/com/project/poorlex/domain/notification/Notification.java
  src/main/java/com/project/poorlex/domain/notification/NotificationRepository.java
  src/main/java/com/project/poorlex/domain/notification/NotificationType.java
  src/main/java/com/project/poorlex/domain/payment/Payment.java
  src/main/java/com/project/poorlex/domain/payment/PaymentRepository.java
  src/main/java/com/project/poorlex/domain/paymentphoto/PaymentPhoto.java
  src/main/java/com/project/poorlex/domain/paymentphoto/PaymentPhotoRepository.java
  src/main/java/com/project/poorlex/domain/vote/Vote.java
  src/main/java/com/project/poorlex/domain/vote/VoteRepository.java
  src/main/java/com/project/poorlex/domain/voteopinion/VoteOpinion.java
  src/main/java/com/project/poorlex/domain/voteopinion/VoteOpinionRepository.java
Labels: 💪 feature

#12 [#11] chore: 환경설정 및 build.gradle 수정
  build.gradle
  src/main/resources/application-jwt.yml
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 👷‍♀️ chore

#13 [#9] feature: redis 설정 추가 및 회원 도메인 변경점
  src/main/java/com/project/poorlex/config/RedisConfig.java
  src/main/java/com/project/poorlex/config/RedisProperties.java
  src/main/java/com/project/poorlex/domain/member/Member.java
  src/main/java/com/project/poorlex/domain/member/MemberRepository.java
  src/main/java/com/project/poorlex/domain/member/MemberRole.java
  src/main/java/com/project/poorlex/util/RedisUtil.java
  src/test/java/com/project/poorlex/config/TestRedisConfig.java
  src/test/java/com/project/poorlex/config/TestRedisServerConfig.java
Labels: 💪 feature

#15 [#14] feature: JWT설정, SpringSecurity 설정 및 회원 로그인
  src/main/java/com/project/poorlex/api/controller/MemberController.java
  src/main/java/com/project/poorlex/api/service/AuthService.java
  src/main/java/com/project/poorlex/api/service/MemberService.java
  src/main/java/com/project/poorlex/config/JwtAccessDeniedHandler.java
  src/main/java/com/project/poorlex/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/project/poorlex/config/SecurityConfig.java
  src/main/java/com/project/poorlex/dto/member/MemberCreateRequest.java
  src/main/java/com/project/poorlex/dto/member/MemberLoginResponse.java
  src/main/java/com/project/poorlex/exception/ApiControllerAdvice.java
  src/main/java/com/project/poorlex/exception/ApiResponse.java
  src/main/java/com/project/poorlex/exception/member/MemberCustomException.java
  src/main/java/com/project/poorlex/exception/member/MemberErrorCode.java
  src/main/java/com/project/poorlex/jwt/JwtTokenProvider.java
  src/main/java/com/project/poorlex/jwt/MemberAuthentication.java
  src/main/java/com/project/poorlex/jwt/Token.java
  src/main/java/com/project/poorlex/jwt/filter/JwtFilter.java
  src/main/java/com/project/poorlex/util/AuthUtil.java
Labels: 💪 feature

#17 [#16] bugfix: TestCode를 위한 메서드 위치 변경
  src/main/java/com/project/poorlex/api/service/AuthService.java
  src/main/java/com/project/poorlex/util/AuthUtil.java
Labels: 🐞 bug

#18 [#10] feature: 배틀 생성 및 조회
  src/main/java/com/project/poorlex/api/controller/BattleController.java
  src/main/java/com/project/poorlex/api/service/BattleService.java
  src/main/java/com/project/poorlex/domain/battle/Battle.java
  src/main/java/com/project/poorlex/domain/battle/BattleFilter.java
  src/main/java/com/project/poorlex/domain/battle/BattleRepository.java
  src/main/java/com/project/poorlex/domain/battle/BattleStatus.java
  src/main/java/com/project/poorlex/dto/battle/BattleCreateRequest.java
  src/main/java/com/project/poorlex/dto/battle/BattleCreateResponse.java
  src/main/java/com/project/poorlex/dto/battle/BattleSearchResponse.java
  src/test/java/com/project/poorlex/domain/battle/BattleServiceTest.java
Labels: 💪 feature

#20 [#19] feature: 회원정보 수정 및 생성로직 수정
  src/main/java/com/project/poorlex/api/controller/MemberController.java
  src/main/java/com/project/poorlex/api/service/MemberService.java
  src/main/java/com/project/poorlex/domain/member/Member.java
  src/main/java/com/project/poorlex/dto/member/MemberCreateRequest.java
  src/main/java/com/project/poorlex/dto/member/MemberUpdateRequest.java
  src/main/java/com/project/poorlex/dto/member/MemberUpdateResponse.java
Labels: 💪 feature

#24 [#23] feature: 마이페이지 조회
  src/main/java/com/project/poorlex/api/controller/MemberController.java
  src/main/java/com/project/poorlex/api/service/MemberService.java
  src/main/java/com/project/poorlex/domain/beggar/Beggar.java
  src/main/java/com/project/poorlex/domain/beggar/BeggarRepository.java
  src/main/java/com/project/poorlex/domain/member/Member.java
  src/main/java/com/project/poorlex/dto/member/MemberResponse.java
  src/main/java/com/project/poorlex/exception/beggar/BeggarCustomException.java
  src/main/java/com/project/poorlex/exception/beggar/BeggarErrorCode.java
Labels: 💪 feature

#26 [#25] test: 회원 테스트 코드
  src/test/java/com/project/poorlex/IntegrationTestSupport.java
  src/test/java/com/project/poorlex/PoorlexApplicationTests.java
  src/test/java/com/project/poorlex/api/controller/MemberControllerTest.java
  src/test/java/com/project/poorlex/api/service/BattleServiceTest.java
  src/test/java/com/project/poorlex/api/service/MemberServiceTest.java
  src/test/java/com/project/poorlex/config/TestSecurityConfig.java
  src/test/java/com/project/poorlex/domain/battle/BattleServiceTest.java
  src/test/java/com/project/poorlex/domain/beggar/BeggarRepositoryTest.java
Labels: 🧪 test
